CREATE DATABASE IF NOT EXISTS stockflow;
USE stockflow;

CREATE TABLE IF NOT EXISTS categorias (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(45) NOT NULL,
  ativo BOOLEAN DEFAULT TRUE,
  dataCad DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS produtos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nomeprod VARCHAR(100) NOT NULL,
  descricao TEXT,
  valor DECIMAL(10,2) NOT NULL,
  idcategoria INT NOT NULL,
  ativo BOOLEAN DEFAULT TRUE,
  dataCad DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (idcategoria) REFERENCES categorias(id)
);

CREATE TABLE IF NOT EXISTS clientes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  telefone VARCHAR(20),
  cpf VARCHAR(14) NOT NULL,
  endereco VARCHAR(255),
  ativo BOOLEAN DEFAULT TRUE,
  dataCad DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS vendedores (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  telefone VARCHAR(20),
  cpf VARCHAR(14) NOT NULL,
  comissao DECIMAL(5,2) DEFAULT 0,
  ativo BOOLEAN DEFAULT TRUE,
  dataCad DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pedidos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  idcliente INT NOT NULL,
  idvendedor INT NOT NULL,
  dataPedido DATETIME DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(20) DEFAULT 'pendente',
  total DECIMAL(10,2) DEFAULT 0,
  ativo BOOLEAN DEFAULT TRUE,
  FOREIGN KEY (idcliente) REFERENCES clientes(id),
  FOREIGN KEY (idvendedor) REFERENCES vendedores(id)
);

CREATE TABLE IF NOT EXISTS itenspedidos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  idpedido INT NOT NULL,
  idproduto INT NOT NULL,
  quantidade INT NOT NULL,
  precoUnitario DECIMAL(10,2) NOT NULL,
  subtotal DECIMAL(10,2) NOT NULL,
  FOREIGN KEY (idpedido) REFERENCES pedidos(id),
  FOREIGN KEY (idproduto) REFERENCES produtos(id)
);
